![Cabecera](../../assets/cabecera_sql.png)

# SQL en Python: WHERE

Bueno, pues ya empezamos con las clausulas WHERE aunque por ahora serán relativamente sencillas. Vamos haciendo las cargas de rigor:

In [1]:
import pandas as pd
import sqlite3

# Conectamos con la base de datos chinook.db
connection = sqlite3.connect("data/chinook.db")

# Obtenemos un cursor que utilizaremos para hacer las queries
cursor_bootcamp = connection.cursor()

Pero antes de empezar...

### Una función muy práctica

Si te fijaste en la sesión anterior repetíamos siempre el mismo código y esquema para hacer una query y luego llevarla a un dataframe. Es en esos casos en los que una función se hace necesaria... por ejemplo:

In [2]:
# Con esta función leemos los datos y lo pasamos a un DataFrame de Pandas
def sql_query(query):

    # Ejecuta la query
    cursor_bootcamp.execute(query) # Recuerda que sólo funcionará si has llamado cursor_bootcamp
                                    # a tu cursor, si no, cambia el nombre en todo el código de la función

    # Almacena los datos de la query 
    ans = cursor_bootcamp.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in cursor_bootcamp.description]

    return pd.DataFrame(ans,columns=names)

Probemos:

In [3]:
query = '''
SELECT composer
FROM tracks
'''
sql_query(query)

                                               Composer
0             Angus Young, Malcolm Young, Brian Johnson
1                                                  None
2     F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...
3     F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...
4                            Deaffy & R.A. Smith-Diesel
...                                                 ...
3498                                               None
3499                                     Franz Schubert
3500                                 Claudio Monteverdi
3501                            Wolfgang Amadeus Mozart
3502                                       Philip Glass

[3503 rows x 1 columns]

### WHERE

Se usa para filtrar filas como ya sabes, veamos algunos ejemplos de uso:

#### Filtros numéricos

* **Un valor numérico**
    * UnitPrice = 0.99
    * UnitPrice >= 0.99
    * UnitPrice < 0.99

In [4]:
# Escogiendo la tabla tracks canciones que duren más de 6 minutos (360000 milisegundos)
minutos = 6
query = f'''
SELECT name "Nombre canción", Milliseconds "Duración"
FROM tracks
WHERE Milliseconds > {minutos * 60 * 1000}
'''

sql_query(query)

                                        Nombre canción  Duración
0                                 Princess of the Dawn    375418
1                                    Let There Be Rock    366654
2                                             Overdose    369319
3                                   Livin' On The Edge    381231
4                          You Oughta Know (Alternate)    491885
..                                                 ...       ...
618  Symphony No. 3 Op. 36 for Orchestra and Sopran...    567494
619                                   Act IV, Symphony    364296
620  3 Gymnopédies: No.1 - Lent Et Grave, No.3 - Le...    385506
621                Symphony No. 2: III. Allegro vivace    376510
622  Concerto for Violin, Strings and Continuo in G...    493573

[623 rows x 2 columns]

Podríamos dejarlo además en segundos operando directamente la columna en la primera parte del SELECT:

In [5]:
minutos = 6
query = f'''
SELECT name "Nombre canción", Milliseconds/1000 "Duración"
FROM tracks
WHERE Milliseconds > {minutos * 60 * 1000}
'''

sql_query(query)

                                        Nombre canción  Duración
0                                 Princess of the Dawn       375
1                                    Let There Be Rock       366
2                                             Overdose       369
3                                   Livin' On The Edge       381
4                          You Oughta Know (Alternate)       491
..                                                 ...       ...
618  Symphony No. 3 Op. 36 for Orchestra and Sopran...       567
619                                   Act IV, Symphony       364
620  3 Gymnopédies: No.1 - Lent Et Grave, No.3 - Le...       385
621                Symphony No. 2: III. Allegro vivace       376
622  Concerto for Violin, Strings and Continuo in G...       493

[623 rows x 2 columns]

#### Filtros sobre campos de texto

* **Un valor string**: Name = 'Restless and Wild'
* **string contenido**:
    * strings que empiecen por 'A': Name like 'A%'
    * strings que acaben en 'A': Name like '%A'
    * strings que lleven 'A' en algun punto: Name like '%A%'

In [6]:
# Compositores que se llaman Brian
query = '''
SELECT *
FROM tracks
WHERE composer LIKE "%Brian%"
'''
sql_query(query)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,6,Put The Finger On You,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205662,6713451,0.99
2,7,Let's Get It Up,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",233926,7636561,0.99
3,8,Inject The Venom,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",210834,6852860,0.99
4,9,Snowballed,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",203102,6599424,0.99
5,10,Evil Walks,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263497,8611245,0.99
6,11,C.O.D.,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",199836,6566314,0.99
7,12,Breaking The Rules,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263288,8596840,0.99
8,13,Night Of The Long Knives,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205688,6706347,0.99
9,14,Spellbound,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",270863,8817038,0.99
10,115,Please Mr. Postman,12,1,5,Brian Holland/Freddie Gorman/Georgia Dobbins/R...,137639,2206986,0.99
11,427,Who Wants To Live Forever,36,1,1,Brian May,297691,9577577,0.99
12,432,Hammer To Fall,36,1,1,Brian May,220316,7255404,0.99
13,1776,You've Been A Long Time Coming,146,1,14,Brian Holland/Eddie Holland/Lamont Dozier,137221,4437949,0.99
14,2125,United Colours,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",330266,10939131,0.99
15,2126,Slug,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",281469,9295950,0.99
16,2127,Your Blue Room,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",328228,10867860,0.99
17,2128,Always Forever Now,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",383764,12727928,0.99
18,2129,A Different Kind Of Blue,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",120816,3884133,0.99
19,2130,Beach Sequence,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",212297,6928259,0.99
20,2131,Miss Sarajevo,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",340767,11064884,0.99
21,2132,Ito Okashi,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",205087,6572813,0.99
22,2133,One Minute Warning,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",279693,9335453,0.99
23,2134,Corpse (These Chains Are Way Too Long),176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",214909,6920451,0.99
24,2135,Elvis Ate America,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",180166,5851053,0.99
25,2136,Plot 180,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",221596,7253729,0.99
26,2137,Theme From The Swan,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",203911,6638076,0.99
27,2138,Theme From Let's Go Native,176,1,10,"Brian Eno, Bono, Adam Clayton, The Edge & Larr...",186723,6179777,0.99
28,2257,Fat Bottomed Girls,185,1,1,"May, Brian",204695,6630041,0.99
29,2261,Save Me,185,1,1,"May, Brian",228832,7444624,0.99
30,2264,Now I'm Here,185,1,1,"May, Brian",255346,8328312,0.99
31,2267,Flash,185,1,1,"May, Brian",168489,5464986,0.99
32,2269,We Will Rock You,185,1,1,"Deacon, John/May, Brian",122880,4026955,0.99
33,2958,Luminous Times (Hold On To Love),234,1,1,Brian Eno/U2,277760,9015513,0.99

#### Filtros varios

  
* **Varios valores**: GenreId in (1, 5, 12)  
* **Distinto de**: UnitPrice <> 0.99

In [9]:
# Clientes que vivan en Berlin, Londres o París
query = '''
SELECT FirstName "Nombre", LastName "Apellido", City "Ciudad"
FROM Customers
WHERE City in("Berlin", "London", "Paris")
'''
sql_query(query)

      Nombre   Apellido  Ciudad
0     Hannah  Schneider  Berlin
1     Niklas   Schröder  Berlin
2    Camille    Bernard   Paris
3  Dominique   Lefebvre   Paris
4       Emma      Jones  London
5       Phil     Hughes  London

#### Combinaciones booleanas de condiciones

Por supuesto podemos combinar los filtros ya que no dejan de ser condiciones booleanas al igual que hacemos con los `DataFrame` de pandas.  Complicando un poco más el `WHERE`

In [12]:
# Busquemos las canciones que cuesten más de 0.99 o duren menos de 3 minutos y además de eso en su nombre aparezca la palabra Fire
query = '''
SELECT *
FROM tracks
WHERE (unitprice > 0.99 or Milliseconds < 3*60*1000 and Name LIKE "%fire%")
'''
sql_query(query)

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1486,Fire,120,1,1,Jimi Hendrix,164989,5383075,0.99
1,1948,Fire Fire,160,1,3,Clarke/Kilmister/Taylor,164675,5416114,0.99
2,2666,Play With Fire,216,1,1,Nanker Phelge,132022,4265297,0.99
3,2819,Battlestar Galactica: The Story So Far,226,3,18,None,2622250,490750393,1.99
4,2820,Occupation / Precipice,227,3,19,None,5286953,1054423946,1.99
...,...,...,...,...,...,...,...,...,...
212,3363,"There's No Place Like Home, Pt. 2",261,3,21,None,2497956,523748920,1.99
213,3364,"There's No Place Like Home, Pt. 3",261,3,21,None,2582957,486161766,1.99
214,3428,Branch Closing,251,3,22,None,1814855,360331351,1.99
215,3429,The Return,251,3,22,None,1705080,343877320,1.99
216,3449,"Music for the Royal Fireworks, HWV351 (1749): ...",315,2,24,George Frideric Handel,120000,2193734,0.99